# Generated by Django 4.1.13 on 2023-12-11 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wedd", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="full_name",
            new_name="fullname",
        ),
    ]
