# Generated by Django 4.1.13 on 2023-12-12 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wedd", "0002_rename_full_name_userprofile_fullname"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="wandekar",
        ),
        migrations.RenameField(
            model_name="wandekar",
            old_name="fullname",
            new_name="full_name",
        ),
    ]
