# Generated by Django 4.1.13 on 2024-01-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wedd", "0003_rename_userprofile_wandekar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="kumbi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("confirmPassword", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=120,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="wandekar",
        ),
    ]
